04/06/2022 03:36:57 PM [INFO]: Preparing model for multi-process MCTS...
04/06/2022 03:36:57 PM [INFO]: Loaded cc4_current_net__iter3.pth.tar model.
04/06/2022 03:36:57 PM [INFO]: Spawning 32 processes...
START TIME:  15:36:44
04/06/2022 03:37:07 PM [INFO]: [CPU: 5]: Starting MCTS self-play...
04/06/2022 03:37:07 PM [INFO]: [CPU: 4]: Starting MCTS self-play...
04/06/2022 03:37:07 PM [INFO]: [CPU: 2]: Starting MCTS self-play...
04/06/2022 03:37:07 PM [INFO]: [CPU: 11]: Starting MCTS self-play...
04/06/2022 03:37:07 PM [INFO]: [CPU: 6]: Starting MCTS self-play...
04/06/2022 03:37:07 PM [INFO]: [CPU: 12]: Starting MCTS self-play...
04/06/2022 03:37:07 PM [INFO]: [CPU: 7]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:07 PM [INFO]: [CPU: 6]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:07 PM [INFO]: [CPU: 4]: Game 0
04/06/2022 03:37:07 PM [INFO]: [CPU: 7]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:07 PM [INFO]: [CPU: 11]: Game 0
04/06/2022 03:37:07 PM [INFO]: [CPU: 5]: Game 0
04/06/2022 03:37:07 PM [INFO]: [CPU: 2]: Game 0
04/06/2022 03:37:07 PM [INFO]: [CPU: 12]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]
  0%|          | 0/5 [00:00<?, ?it/s]





Process Process-7:
Process Process-3:
Process Process-13:
Process Process-12:
Process Process-5:
Process Process-8:
Process Process-6:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
Traceback (most recent call last):
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
Traceback (most recent call last):
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
Traceback (most recent call last):
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:08 PM [INFO]: [CPU: 9]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:08 PM [INFO]: [CPU: 9]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-10:
04/06/2022 03:37:08 PM [INFO]: [CPU: 0]: Starting MCTS self-play...
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:09 PM [INFO]: [CPU: 0]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-1:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:10 PM [INFO]: [CPU: 14]: Starting MCTS self-play...
04/06/2022 03:37:10 PM [INFO]: [CPU: 17]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:10 PM [INFO]: [CPU: 17]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:10 PM [INFO]: [CPU: 14]: Game 0
04/06/2022 03:37:10 PM [INFO]: [CPU: 3]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:10 PM [INFO]: [CPU: 3]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-15:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-18:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-4:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:11 PM [INFO]: [CPU: 18]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 18]: Game 0
04/06/2022 03:37:11 PM [INFO]: [CPU: 1]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 1]: Game 0
04/06/2022 03:37:11 PM [INFO]: [CPU: 13]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-19:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:11 PM [INFO]: [CPU: 8]: Starting MCTS self-play...
04/06/2022 03:37:11 PM [INFO]: [CPU: 16]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 13]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 8]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 16]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-2:
04/06/2022 03:37:11 PM [INFO]: [CPU: 20]: Starting MCTS self-play...
04/06/2022 03:37:11 PM [INFO]: [CPU: 21]: Starting MCTS self-play...
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:11 PM [INFO]: [CPU: 10]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 20]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 21]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 10]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-14:
04/06/2022 03:37:11 PM [INFO]: [CPU: 23]: Starting MCTS self-play...
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:11 PM [INFO]: [CPU: 19]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-9:
04/06/2022 03:37:11 PM [INFO]: [CPU: 24]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-17:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:11 PM [INFO]: [CPU: 26]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 24]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 19]: Game 0
04/06/2022 03:37:11 PM [INFO]: [CPU: 23]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-21:
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-22:
  0%|          | 0/5 [00:00<?, ?it/s]  0%|          | 0/5 [00:00<?, ?it/s]
04/06/2022 03:37:11 PM [INFO]: [CPU: 26]: Game 0
Process Process-11:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-25:
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-20:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-24:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-27:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:11 PM [INFO]: [CPU: 27]: Starting MCTS self-play...
04/06/2022 03:37:11 PM [INFO]: [CPU: 22]: Starting MCTS self-play...
04/06/2022 03:37:11 PM [INFO]: [CPU: 15]: Starting MCTS self-play...
04/06/2022 03:37:11 PM [INFO]: [CPU: 25]: Starting MCTS self-play...
04/06/2022 03:37:11 PM [INFO]: [CPU: 29]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 27]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 15]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 22]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 29]: Game 0
04/06/2022 03:37:11 PM [INFO]: [CPU: 31]: Starting MCTS self-play...
04/06/2022 03:37:11 PM [INFO]: [CPU: 30]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 25]: Game 0
04/06/2022 03:37:11 PM [INFO]: [CPU: 28]: Starting MCTS self-play...
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 31]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 30]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]04/06/2022 03:37:11 PM [INFO]: [CPU: 28]: Game 0
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-16:
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-28:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Traceback (most recent call last):
  0%|          | 0/5 [00:00<?, ?it/s]
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Process Process-23:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-30:
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-26:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-32:
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-31:
  0%|          | 0/5 [00:00<?, ?it/s]
Process Process-29:
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
Traceback (most recent call last):
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 178, in MCTS_self_play
    root = UCT_search(current_board,777,connectnet,t)
  File "/home/x_aolss/gym_connect4/gym-connect4/MCTS_c4.py", line 136, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 89, in forward
    s = self.conv(s)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/gym_connect4/gym-connect4/alpha_net_c4.py", line 32, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/x_aolss/.conda/envs/myownenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)
04/06/2022 03:37:13 PM [INFO]: Finished multi-process MCTS!
FINISHED SELF PLAY:  15:37:13
